package nl.wouterdebruijn.EasyH2O;

import java.sql.*;

public class MySQLConnector {
    Connection con;

    /**
     * Connect to MySQL Database
     *
     * @param hostname hostname of SQL Server (localhost / 127.0.0.1 / 192.168.1.1 / example.org
     * @param user     Username for SQL login
     * @param database Database for SQL Login
     * @param password Password of SQL User
     * @throws SQLException Login fails, throws error.
     */
    public void connect(String hostname, String user, String database, String password) throws SQLException {
        /*
          getConnection requires a connection string, in newer version the username and password aren't added to thing string, but provided as extra arguments.
          The String is generated by using the String.format function. Hostname and dbName are inserted.
         */
        this.con = DriverManager.getConnection(String.format("jdbc:mysql://%s/%s", hostname, database), user, password);
    }

    public void disconnect() throws SQLException {
        if (this.con != null) this.con.close();
    }

    public ResultSet query() throws SQLException {
        Statement stmt = this.con.createStatement();
        String query = "select * from users;";
        return stmt.executeQuery(query);

    }
}
