package nl.wouterdebruijn.EasyH2O;

import java.sql.*;

public class MySQLConnector
	{
		Connection con;

		String hostname = "";
		String user = "";
		String database = "";
		String password = "";

		public void connect() throws SQLException
			{
				/*
				  getConnection requires a connection string, in newer version the username and pasword aren't added to thing string, but provided as extra arguments.
				  The String is generated by using the String.format function. Hostname and dbName are inserted.

				  To change the hostname / db / username / password please use the String variables above.
				 */
				this.con = DriverManager.getConnection (String.format("jdbc:mysql://%S/%S", hostname, database), user, password);
			}


		public void disconnect() throws SQLException
			{
				this.con.close ();
			}
			
		public ResultSet query() throws SQLException
			{
				Statement stmt = this.con.createStatement();
				String query = "select * from users;";
				return stmt.executeQuery(query);
				
			}
	}
